name: Github CI

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: >-
          sudo apt-get update

          sudo apt-get install -y libpng-dev libsamplerate0-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl1.2-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev
      - name: checkout
        uses: actions/checkout@v2
      - name: autogen
        run: >-
          autoreconf -fi
          
          ./configure "$@"
      - name: make
        run: make
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: binary
          path: /home/runner/work/psdoom-ng/psdoom-ng/src/psdoom-ng*
